### ISSUE TITLE
[BUG] Issue when importing more than one library generated with prefabPublishing

### ISSUE THREAD

**Issue by Consti10** [google/prefab#118]
**Describe the bug**
I have issues importing more than one library generated with prefabPublishing enabled.
When I only add library a or b to the project it builds fine.
When I both add library a and b to the project it throws the error message 
`2 files found with path 'lib/armeabi-v7a/libc++_shared.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/r/tools/jniLibs-vs-imported-targets`

**To Reproduce**
I have created 3 commits to a basic example project that show the issue.
Commit 1 adds library a and works fine.
Commit 2 adds library b and works fine.
Commit 3 adds both library a and b and throws the error from above:

[Here is the github repository](https://github.com/Consti10/ndk-samples)

And here are the 3 commits:
https://github.com/Consti10/ndk-samples/commit/f776f647756221218a80f3bbaf82d27509670c5f
https://github.com/Consti10/ndk-samples/commit/4f5d73767a2c4218bb8f3595000fc0caa9c22391
https://github.com/Consti10/ndk-samples/commit/8fb426ebfab6cecf6d05162036329d63c290df17

**Comment by Consti10** [comment]
#116

**Comment by Consti10** [comment]
I especially mentioned prefabPublishing as the curl-ssl example adds more than one prefab library (curl and ssl ) and does not have these issues.
However, as far as I know both curl and ssl were generated by 'ndkPorts' and not via prefabPublishing

**Comment by DanAlbert** [comment]
This isn't related to prefab. You'll need to file an AGP bug. For future reference, everything related to gradle probably belongs there, not here. This is just for the `prefab` command line tool, whose only job is creating the cmake/ndk-build scripts from a `prefab` directory such as is in an AAR; and the prefab package format. None of the integration with AGP lives here.

When you file that bug, the problem is that adding the dependency is causing the libraries in the `jni` directory of the AAR to be included even though they are not used. The error is correct that there is a duplicate in what is trying to be installed to the APK, but afaik there is no way to depend on an AAR without depending on _all_ of an AAR.

**Comment by alexcohn** [comment]
All you need, add to your app's **build.gradle**

    android.packagingOptions.pickFirst("lib/*/libc++_shared.so")

**Comment by DanAlbert** [comment]
That will work around the bug, yes. I still think it's an AGP bug that you can't do this though.

**Comment by Consti10** [comment]
Thanks for the workaround. I forgot to link the agp bug, it is here:
https://issuetracker.google.com/issues/168777344

**Comment by alexcohn** [comment]
> That will work around the bug, yes. I still think it's an AGP bug that you can't do this though.

You probably refer to https://issuetracker.google.com/issues/154133927.

Actually, there is another workaround, which may help sometimes: add to library **build.gradle**

    android.packagingOptions.exclude("**.so")

Now the AAR will come with no `jni` directory, and the app will build flawlessly.

**Comment by wongk** [comment]
See also https://issuetracker.google.com/issues/181046700 and https://issuetracker.google.com/issues/178594839.

**Comment by haris523** [comment]
> All you need, add to your app's **build.gradle**
> 
> ```
> android.packagingOptions.pickFirst("lib/*/libc++_shared.so")
> ```

It wasn't for this package, but it managed to fix an issue I couldn't find an answer to any where else.
