### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gezilinll** [google/prefab#138]
**Describe the bug**
Build aar1 and aar2 with Prefab feature, and aar1 depend on ffmpeg.so, aar2 depend on aar1 and use ffmpeg interface, run on android devices which os api is 5.1 and below will System.loadLibrary("aar2") failed.

`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_freep" referenced by "/data/app/com.example.xplayer-2/lib/arm64/libXPlayer.so"...`

Devices above 5.1 will load success, if I config ffmpeg.so in CMakeLists.txt from aar2 then 5.1 and below success too.
I found aar1Config.cmake file INTERFACE_LINK_LIBRARIES is empty, if I config ffmpeg.so path here will work too. 

**Environment:**
Prefab version: 1.1.3
Device: Oppo A59s

**Comment by DanAlbert** [comment]
I don't know what I can do without a repro case. We don't have an AAR for ffmpeg so idk if the bug is with your AAR or with prefab.

https://github.com/KeepSafe/ReLinker is usually the answer to "works on newer versions of Android" though.

Closing but will reopen if we get the info we need to proceed.

**Comment by LinBinghe** [comment]
thx, but ReLinker not working, not only ffmpeg, it's all the symbol in transitive libraries won't be found by aar2, include glesv3、jni-graphics ... in ndk, but if I compile by aar2.cmake depend on aa1.cmake instead of Prefab feature，Oppo A59s will loadLibrary success.
I curious about is there something different with 5.1 below and above, and how can I make ffmpeg included to `exported_libraries` in module.json, I can't found more info about config in gradle or other way.
