### ISSUE TITLE
[BUG] Prefab does not detect libraries when built with the CMake `<CONFIG>_POSTFIX` or `OUTPUT_NAME` properties

### ISSUE THREAD

**Issue by Lectem** [google/prefab#147]
**Describe the bug**
Prefab does not respect CMake's [`<CONFIG>_POSTFIX`](https://cmake.org/cmake/help/latest/prop_tgt/CONFIG_POSTFIX.html#prop_tgt:%3CCONFIG%3E_POSTFIX) target property. Same issue with the [`OUTPUT_NAME`](https://cmake.org/cmake/help/latest/prop_tgt/OUTPUT_NAME.html) property.
This means that any package produced where the `<CONFIG>_POSTFIX` property is set will not find the library correctly (even though it included it in the package!)

**To Reproduce**
1. Create any library with CMake
2. Use `set_target_properties(<YOUR_TARGET> PROPERTIES DEBUG_POSTFIX d)` to set the POSTFIX for the `Debug` configuration
3. Build the project in debug and publish the .aar using gradle + prefab
4. Import the .aar in another project using gradle + prefab

**Expected behavior**
Prefab should be able to find the library (which is correctly included in the `.arr`, with the postfix.).

**Logs**
```
Error while executing java process with main class com.google.prefab.cli.AppKt with arguments {--build-system cmake --platform android --abi armeabi-v7a --os-version 21 --stl c++_static --ndk-version 23 --output D:\NativeAndroidApp\app\.cxx\Debug\4vh4t351\prefab\armeabi-v7a\prefab C:\Users\Lectem\.gradle\caches\transforms-3\7c3a2cd93ebaf3c2b65f6afd771ccb29\transformed\jetified-myrpoject-debug\prefab}

Exception in thread "main" java.lang.RuntimeException: Prebuilt directory does not contain mylibrary.a or mylibrary.so: C:\Users\Lectem\.gradle\caches\transforms-3\7c3a2cd93ebaf3c2b65f6afd771ccb29\transformed\jetified-myrpoject-debug\prefab\modules\mylibrary\libs\android.arm64-v8a
	at com.google.prefab.api.ElfKt.findElfLibrary(Elf.kt:44)
	at com.google.prefab.api.Android.libraryFileFromDirectory(Android.kt:385)
	at com.google.prefab.api.PrebuiltLibrary.<init>(PrebuiltLibrary.kt:48)
```

**Environment:**
Prefab version: 2.0.0

Host OS: Windows 10
Target platform: Android
Target ABI: Any
Target OS version: Any
Build system: Gradle

**Comment by DanAlbert** [comment]
There are a few unrelated pieces of software at play here. I'm probably going to be overly verbose just to make sure we're on the same page :)

AGP is responsible for creating the prefab packages that get included in AARs. This is step 3 in your list. If the package is being generated incorrectly, the bug is in AGP.

Prefab is the command line tool that consumes the `prefab/` subdirectory of an AAR (or from whatever source, the AAR is just the most common distribution method) and generates build scripts (in this case CMake package configs) that can be imported by your build system. This is step 4 in your list. If there's data in the prefab metadata that isn't making it into the build scripts, that's a prefab bug. If there's data that cannot be described by prefab, that's a prefab feature request.

I think there are two things here. The first of which is a bug where AGP is not aware of the name difference, so there is a bug in AGP there. That needs to be [filed against AGP](https://developer.android.com/studio/report-bugs#build-bugs) rather than here; prefab is doing the right thing, it's just being fed a broken package.

The second thing that might be here is a feature request for prefab to support build variants like debug/release explicitly. I don't know if this is feasible because while debug/release are fairly widely accepted build variants, many systems include others (CMake has things like `MinSizeRelease` and `RelWithDebInfo`), and others like AGP allow arbitrary addition of more build variants on a per module basis. I think a better way to handle this would be to keep the gradleisms in gradle: build variants of the AAR for each build flavor and let your dependencies vary by build flavor while keeping the imported package/module names in cmake the same.

lmk if any of that doesn't match with your understanding. If it all seems right, file the AGP bug and paste the link here so I can CC myself :)

**Comment by DanAlbert** [comment]
Closing for lack of feedback.
