### ISSUE TITLE
[PKG] Sodium

### ISSUE THREAD

**Issue by davnat** [google/prefab#29]
**Package name**
Sodium

**Package URL**
https://libsodium.gitbook.io/doc/

**Package source location**
https://github.com/jedisct1/libsodium

**Comment by ReenigneCA** [comment]
I'm not associated with this project or libsodium, but I had a push request accepted to update the libsodium build scripts for android a while back and have just finished (I hope :P) a [push request that includes a build script to generate an AAR for libsodium.](https://github.com/jedisct1/libsodium/pull/1155). The script is just a shell script that leverages the existing build system for libsodium then generates a prefab directory structure with metadata and places library versions where they need to be. You end up with an AAR that contains modules sodium sodium-static sodium-minimal and sodium-minimal-static which all mean what you think they should mean :P. 

Given sodium is a crypto library you likely want to use the stable version which has the old build scripts. You can download the stable version then just overwrite the dist-build folder with the dist-build folder from the master branch and it will build a stable version AAR.

Personally I'd like to see the AAR go into Maven but I leave that between the established developers here and in the libsodium project.

**Comment by DanAlbert** [comment]
Fantastic! Everything works much more smoothly if the library authors manage these themselves (like you say, especially for something security sensitive!), so that's great news.

I'll mark this closed then. Agreed that it'd be best to get it into maven but it's probably best for the authors to do that. They'll stay on top of updates and changes better than we can. If I can be of help for that lmk, but I don't have any leverage with libsodium so I doubt it :)

Thanks a lot for making that happen!
